# Generated by Django 4.1.3 on 2023-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_trip_driver_rider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
